/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes version 20221116 of the Meem Agreement Contract metadata standard.
 */
export type Meem_AgreementContract_20221116 = Meem_AgreementContract_202211161 & Meem_AgreementContract_202211162;
export type Meem_AgreementContract_202211161 = Meem_Contract_20221116;

/**
 * This schema describes the 20221116 version of the Meem Contract metadata standard.
 */
export interface Meem_Contract_20221116 {
  /**
   * The type of metadata. See supported Meem metadata types here: https://meem.wtf
   */
  meem_metadata_type: string;
  /**
   * The calendar version of the Meem metadata schema. See supported Meem metadata schemas here: https://meem.wtf
   */
  meem_metadata_version: string;
  /**
   * The description of the contract.
   */
  description: string;
  /**
   * The name of the contract.
   */
  name: string;
  /**
   * An optional image for the contract.
   */
  image?: string;
  /**
   * An optional url to a website with more information about the contract.
   */
  external_url?: string;
  [k: string]: unknown;
}
export interface Meem_AgreementContract_202211162 {
  /**
   * The instructions for applying to join the club's agreement contract.
   */
  application_instructions?: string[];
  [k: string]: unknown;
}
