/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes version 20221116 of the Meem Metadata standard.
 */
export interface Meem_Metadata_20221116 {
  /**
   * The type of metadata. See supported Meem metadata types here: https://meem.wtf
   */
  meem_metadata_type: string;
  /**
   * The calendar version of the Meem metadata schema. See supported Meem metadata schemas here: https://meem.wtf
   */
  meem_metadata_version: string;
  [k: string]: unknown;
}
